export default {
  LANDING_PAGE_TITLE: 'Reimagining Professional Connections',
  FULL_NAME: 'Full Name',
  EMAIL_ADDRESS: 'Email Address',
  JOIN_US: 'Join Us',
  JOIN_US_SUB_HEADING: 'Be a part of something new',
  NOT_A_ROBOT: 'I’m not a robot',
  I_AM_AGREE: 'I agree to the ',
  TERMS_CONDITIONS: 'Terms & Conditions',
  SCHOOL_TITLE: 'Multiple schools? You can add these later',
  WHERE_YOU_WORK: 'Where do you work?',
  JOB_TITLE: 'What’s your job title?',
  LAST_SCHOOL_ATTENTED: 'What is the last school you attended?',
  ADD_WORK_PALCE: 'Add a workplace',
  ADD_JOB_TITLE: 'Add your job title',
  ADD_SCHOOL: 'Add your school',
  PRONOUN: 'What are your pronouns?',
  BIRTHDAY_TITLE: 'When is your birthday?',
  BITHDAY_SUB_TITLE: 'Don’t worry, this won’t be part of your public profile',
  DOB_HINT: 'Day    |      Month      |    Year',
  WHERE_YOU_LIVE: 'Set your location to find connections in your area.',
  SET_LOCATION:
    'Set your location so we can Pitch you the best connections near you',
  CITY_PLACEHOLDER: 'City',
  COUNTRY_PLACEHOLDER: 'Country',
  LOG_IN: 'Log In',
  LOG_OUT: 'Log Out',
  READY_TO_PITCH: 'Ready to pitch?',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  PHONE: 'Phone',
  FORGOT_YOUR_PASSWORD: 'Forgot your password? ',
  SIGN_IN_WITH_GOOGLE: 'Sign in with Google',
  SIGN_IN_WITH_APPLE: 'Sign in with AppleID',
  FORGOT_PASSWORD: 'Forgot Password?',
  FORGOT_PASSWORD_SCREEN_TEXT:
    'Enter the email you used to create your account and we will send you instructions for how to reset your password',
  SEND_INSTRUCTIONS: 'Send Instructions',
  ENTER_CODE: 'Enter 4-digit code',
  VERIFY_CODE: 'Verify your phone',
  ENTER_CODE_EMAIL: 'Your code was emailed to ',
  VERIFY: 'Verify',
  CREATE_YOUR_PASSWORD: 'Create New Password',
  CREATE_PASSWORD: 'Create Password',
  CONFIRM_PASSWORD: 'Confirm Password',
  CHANGE_PASSWORD: 'Change Password',
  STATE_PLACEHOLDER: 'State',
  THIS_SOUNDS_FUN: "This sounds fun, let's do it!",
  NOT_CAMERA_READY_TEXT: 'I am not camera ready at this moment',
  MAKE_YOUR_PITCH: 'Make your Pitch!',
  CREATE_YOUR_OWN: 'Create your own video and personalize your intro!',
  VIEW_SAMPLE_PITCH: 'View a sample Pitch video!',
  NEED_SOME_HELP: 'I need some help with this!',
  READY_TO_RECORD: "I'm ready to record!",
  YOUR_PITCH_VIDEO_HELP: 'Your Pitch video will help you stand out',
  CREATE_A_VIDEO_TITLE: 'Create a 20 second video telling us about yourself!',
  HOW_TO_CREATE_VIDEO_TEXT: 'How to create your Pitch video',
  VIDEO_GET_STARTED: "Here's some help to get you started",
  Next: 'Next',
  HINT_ANSWER: 'Answer',
  SELECT_ALL: '*Select all that apply',
  ENTER_NUMBER: 'Enter your mobile number',
  DONT_WORRY_YOUR: 'Don’t worry, your phone number will be private',
  SEND_CODE: 'Send Code',
  VERIFY_PHONE: 'Verify your phone',
  RESEND_CODE: 'Resend Code',
  BOTH_PASSWORD_MATCH: '*Both passwords much match',
  step1Title: 'One',
  step2Title: 'Two',
  step3Title: 'Three',
  step4Title: 'Four',
  step5Title: 'Five',
  step1Text: 'Tell us your name',
  step2Text: 'Where are you from?',
  step3Text: 'Tell us something you are proud of',
  step4Text: 'Tell us about your values',
  step5Text: 'Tell us what you’re looking to do on Pitch!',
  THIS_VIDEO: 'This video is your time to introduce us to YOU. Make it count!',
  stepTitle1: 'Step 1',
  stepTitle2: 'Step 2',
  stepTitle3: 'Step 3',
  stepTitle4: 'Step 4',
  stepText1: 'Check your lighting!\n(FIND YOUR BEST LIGHT)',
  stepText2:
    'Practice! 20 seconds is quick. What do you want us to know about you in 20 seconds?',
  stepText3: 'Set camera up in a steady place and take a sample video first',
  stepText4: 'Let’s get to recording!',
  PITCH_BEST: '“Pitch” your best face forward!',
  SKIP_FOR_NOW: 'Skip for now',
  CHOOSE_PHOTO: 'Choose Photo',
  RECORD_VIDEO: 'Record Video',
  DO_LATER: 'I’ll do it later!',
  GO_BACK: 'Go back',
  THE_BEAST: 'The best connections are made when you include a photo or video',
  ARE_YOU_SURE: 'Are you sure?',
  DONT_HAVE_ACCOUNT: "Don't have an account? ",
  SIGN_WITH_GOOGLE: 'Sign in with Google',
  SIGN_WITH_APPLE: 'Sign in with AppleID',
  CLICK_HERE: 'Click here',
  OR: 'OR',
  CHOOSE_ANY_PROMPT: 'Choose any prompt',
  MSG_APP_IS_IN_DEVELOPMENT:
    'You have successfully completed the onboarding steps. currently the app is in development so we are not able to proceed further',
  PROFILEPICTITLE: 'PROFILE PICTURE/VIDEO',
  FIRSTNAME: 'FIRST NAME',
  LASTNAME: 'LAST NAME',
  PROFILEJOBTITLE: 'JOB TITLE',
  CURRENTLOCATION: 'CURRENT LOCATION',
  ACCOUNT: 'Account',
  PRIVACY: 'Privacy Policy',
  NOTIFICATIONS: 'Notifications',
  HELP: 'Help',
  COVER_PHOTO: 'COVER PHOTO',
  TAG_LINE: 'TAG LINE',
  PRIVACY_POLICY: 'Privacy Policy',
  REPORT_PROBLEM: 'Report a Problem',
  CONTACT_US: 'Contact Us',
};
